// Loads the Rust/WASM editor core. Generated by `just wasm`.
import init, { call_end, summarize } from "./wasm/cetz_wasm";

export async function initCore(): Promise<void> {
  await init();
}

export { call_end, summarize };
