// Loads the Rust/WASM editor core. Generated by `just wasm`.
import init, { apply_edit, call_end, expr, scene, summarize } from "./wasm/cetz_wasm";

export async function initCore(): Promise<void> {
  await init();
}

export { apply_edit, call_end, expr, scene, summarize };
